y branch
Signed-off-by: cyclinder <qifeng.guo@daocloud.io>

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -30,26 +30,40 @@ jobs:
       - name: Get Ref
         id: get_ref
         run: |
+          tag=""
           if ${{ github.event_name == 'workflow_dispatch' }} ; then
             echo "call by self workflow_dispatch"
-            echo ::set-output name=tag::${{ github.event.inputs.tag }}
+            # check tag if valid
+            grep -Eo "v[0-9]+.[0-9]+.[0-9]" <<< ${{ github.event.inputs.tag }} || ' echo "input tag invalid!"; exit 1 '
+            tag=${{ github.event.inputs.tag }}
             echo ::set-output name=branch::main
           elif ${{ github.event_name == 'push' }} ; then
             echo "call by push tag"
-            echo ::set-output name=tag::${GITHUB_REF##*/}
+            tag=${GITHUB_REF##*/}
             echo ::set-output name=branch::${GITHUB_REF##*/}
           else
             echo "unexpected event: ${{ github.event_name }}"
             exit 1
           fi
 
+          echo "tag: ${tag}"
+          echo "tag=${tag}" >> $GITHUB_OUTPUT
+          Ybranch=$(grep -Eo "v[0-9]+\.[0-9]+\.0" <<< "${tag}") ||  echo "no create Ybranch..."
+          echo "Ybranch: ${Ybranch} "
+          if [ -n "${Ybranch}" ] ; then
+             echo "create Ybranch..."
+             echo "create_Ybranch=true" >> $GITHUB_OUTPUT
+          else
+             echo "create_Ybranch=false" >> $GITHUB_OUTPUT
+          fi
+
       - name: Checkout
-        if: ${{ github.event_name == 'push' }}
         uses: actions/checkout@v3
         with:
           ref: ${{ steps.get_ref.outputs.branch }}
 
       - name: Create branch
+        if: ${{ steps.get_ref.outputs.create_Ybranch == 'true' }}
         uses: peterjgrainger/action-create-branch@v2.2.0
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -82,20 +96,6 @@ jobs:
         with:
           name: binary_files
           path: ./
-
-      - name: Create Release
-        id: create_release
-        uses: ncipollo/release-action@v1.9.0
-        with:
-          artifacts: "*.tar"
-          allowUpdates: true
-          removeArtifacts: true
-          replacesArtifacts: true
-          generateReleaseNotes: true
-          artifactErrorsFailBuild: true
-          token: ${{ secrets.GITHUB_TOKEN }}
-          tag: ${{ needs.get_ref.outputs.tag }}
-          name: "Release ${{ needs.get_ref.outputs.tag }}"
 
   Generate-Changelog-to-file:
     runs-on: ubuntu-latest
